project-1-packages/CommunitySite/main/default/objects/Product2/fields/Featured__c.field-meta.xml
<CustomField>
    <fullName>Featured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Featured</label>
    <type>Checkbox</type>
</CustomField>

project-1-packages/CommunitySite/main/default/objects/Product2/fields/Menu_Type__c.field-meta.xml
<CustomField>
    <fullName>Menu_Type__c</fullName>
    <label>Menu Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>coffee</fullName>
            </value>
            <value>
                <fullName>sandwich</fullName>
            </value>
            <value>
                <fullName>snacks</fullName>
            </value>
            <value>
                <fullName>sweets</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

project-1-packages/CommunitySite/main/default/objects/Product2/fields/Seasonal__c.field-meta.xml
<CustomField>
    <fullName>Seasonal__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Seasonal</label>
    <type>Checkbox</type>
</CustomField>

project-1-packages/CommunitySite/main/default/classes/ProductHelper.cls
public without sharing class ProductHelper {
    

    @AuraEnabled(cacheable=true)
    public static List<id> getSeasonalProductIds(){
        try {
            List<id> productIds = new List<id>();

            for(Product2 product: [SELECT id, Seasonal__c FROM Product2 WHERE Seasonal__c = true LIMIT 3 ]){
                productIds.add(product.id);
            }
            
            return productIds;

        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Product2> getFeaturedProducts(){
        try {
            return [SELECT name,description, Featured__c FROM Product2 WHERE Featured__c = true LIMIT 5];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<Product2> getProductsByType(String type){
        try {
            return [SELECT name,description,Menu_Type__c FROM Product2 WHERE Menu_Type__c = :type];
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}